version: "3.3"
services:
  SaferFire-Backend:
    image: ghcr.io/mo-pr/saferfire
    ports:
      - 3030:3030
    container_name: SaferFire-Backend
    restart: always
    command: bash -c 'pm2 start dist/main.js --name SaferFire-Backend && pm2 startup && pm2 save --force && tail -F anything'