version: "3.8"
services:
  saferFire-backend:
    image: sghcr.io/mo-pr/saferfire-backend
    build:
      context: ./src
    ports:
      - 3030:3030
    container_name: saferFire-backend
    restart: always
    command: bash -c 'pm2 start dist/main.js --name SaferFire-Backend && pm2 startup && pm2 save --force && tail -F anything'