name: build and deploy docker images
on:
 push:
    branches: [ release ]
env:
  REGISTRY: ghcr.io
jobs:
  build:
    name: build and push docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build docker images
        run: | 
          pwd
          ls -al
          docker-compose build
        working-directory: docker-demo
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
      - name: push docker images
        run: |
          docker-compose push
        working-directory: docker-demo
  deployment:
    needs:
      - build
    name: ssh and scp to deployment vm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install ssh key
        uses: caberger/install-ssh-key@v1.0
        with: 
          ssh-private-key:  ${{ secrets.SSH_SERVER_PRIVATE_KEY }}
          user: ${{ secrets.SERVER_USER }}
          server: ${{ secrets.SERVER }}
          alias: server
       - name: Run install.sh on VM  
          working-directory: docker-demo
          run: |
            pwd
            ls -al
            ssh server "rm -rf ~/dist && mkdir -p ~/dist"
            echo "running installation on server..."
            ssh server "cd ~/dist && touch iwashere.txt"
            echo "done $(date)"